name: Kubernetes Setup

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup-k8s:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache: true

    - name: Install dependencies
      run: |
        go mod download
        go mod verify

    # - name: Run tests
    #   run: go test -v -race -coverprofile=coverage.out ./...

    - name: Build binary
      run: |
        go build -v -o k8s-installer ./cmd/installer
        chmod +x k8s-installer

    - name: Run installer (fast mode)
      run: |
        sudo ./k8s-installer -skip-api-wait -verbose

    - name: Wait for components to stabilize
      run: sleep 10

    - name: Verify Kubernetes cluster
      run: |
        export PATH=$PATH:./kubebuilder/bin
        export KUBECONFIG=$HOME/.kube/config   # 🔑 используем kubeconfig
        kubectl get nodes || echo "Nodes check failed"
        kubectl get pods -A || echo "Pods check failed"
        kubectl version --client || echo "Version check failed"

    - name: Create test deployment
      run: |
        export PATH=$PATH:./kubebuilder/bin
        export KUBECONFIG=$HOME/.kube/config   # 🔑 используем kubeconfig
        kubectl create deployment nginx --image=nginx:latest || echo "Deployment creation failed"
        sleep 15
        kubectl get deployments || echo "Deployments check failed"
        kubectl get pods || echo "Pods check failed"

    - name: Upload coverage
      if: always()
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.out
        flags: unittests
        name: codecov-k8s-installer
      continue-on-error: true

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: k8s-logs
        path: /var/log/kubernetes/
        retention-days: 7
      continue-on-error: true

    - name: Upload binary
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: k8s-installer
        path: k8s-installer
        retention-days: 30
