name: Kubernetes Setup

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup-k8s:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache: true

    - name: Install dependencies
      run: |
        go mod download
        go mod verify

    - name: Build binary
      run: |
        go build -v -o k8s-installer ./cmd/installer
        chmod +x k8s-installer

    - name: Run installer
      run: |
        sudo ./k8s-installer -skip-api-wait -verbose

    - name: Wait for stabilization
      run: sleep 60

    # Критичный шаг: проверяем и исправляем kubeconfig
    - name: Fix kubeconfig if needed
      run: |
        echo "=== Checking kubeconfig state ==="
        
        if [ ! -f "$HOME/.kube/config" ]; then
          echo "ERROR: kubeconfig not found"
          exit 1
        fi
        
        cat $HOME/.kube/config
        
        echo ""
        echo "=== Parsing server URL ==="
        SERVER_URL=$(kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}' 2>/dev/null || echo "")
        echo "Current server: '$SERVER_URL'"
        
        # Если kubeconfig пустой или неправильный - пересоздаём
        if [[ -z "$SERVER_URL" ]] || [[ "$SERVER_URL" != "https://127.0.0.1:6443" ]]; then
          echo ""
          echo "WARNING: kubeconfig is invalid or empty, recreating..."
          
          export PATH=$PATH:./kubebuilder/bin
          
          # Проверяем наличие сертификатов
          if [ ! -f "/var/lib/kubernetes/pki/ca.crt" ]; then
            echo "ERROR: CA certificate not found"
            sudo ls -la /var/lib/kubernetes/pki/ || true
            exit 1
          fi
          
          echo "Found certificates:"
          sudo ls -la /var/lib/kubernetes/pki/
          
          # Настраиваем cluster
          kubectl config set-cluster local-cluster \
            --server=https://127.0.0.1:6443 \
            --certificate-authority=/var/lib/kubernetes/pki/ca.crt \
            --embed-certs=true
          
          # Настраиваем credentials
          kubectl config set-credentials admin \
            --client-certificate=/var/lib/kubernetes/pki/admin.crt \
            --client-key=/var/lib/kubernetes/pki/admin.key \
            --embed-certs=true
          
          # Настраиваем context
          kubectl config set-context local-context \
            --cluster=local-cluster \
            --user=admin
          
          # Используем context
          kubectl config use-context local-context
          
          echo ""
          echo "=== Kubeconfig recreated ==="
        else
          echo ""
          echo "kubeconfig is valid"
        fi
        
        echo ""
        echo "=== Final kubeconfig ==="
        kubectl config view --minify
        
        echo ""
        echo "=== Verify server URL ==="
        FINAL_SERVER=$(kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}')
        echo "Server: $FINAL_SERVER"
        
        if [[ "$FINAL_SERVER" != "https://127.0.0.1:6443" ]]; then
          echo "ERROR: Server URL is still wrong!"
          exit 1
        fi
        
        echo "SUCCESS: kubeconfig correctly configured"

    - name: Test API TCP connection
      run: |
        echo "=== Testing TCP connection to API server ==="
        
        for i in {1..30}; do
          if timeout 3 bash -c 'cat < /dev/null > /dev/tcp/127.0.0.1/6443' 2>/dev/null; then
            echo "Connected to 127.0.0.1:6443 (attempt $i)"
            exit 0
          fi
          echo "Attempt $i/30 failed, retrying in 2 seconds..."
          sleep 2
        done
        
        echo "ERROR: Cannot connect to 127.0.0.1:6443 after 30 attempts"
        echo ""
        echo "=== Diagnostics ==="
        ps aux | grep kube-apiserver | grep -v grep || echo "API server not running"
        sudo netstat -tlnp | grep -E ':(6443|8080)' || echo "No listeners"
        exit 1

    - name: Test kubectl client
      run: |
        export PATH=$PATH:./kubebuilder/bin
        export KUBECONFIG=$HOME/.kube/config
        
        echo "=== kubectl client version ==="
        kubectl version --client

    - name: Get cluster info
      run: |
        export PATH=$PATH:./kubebuilder/bin
        export KUBECONFIG=$HOME/.kube/config
        
        echo "=== Cluster info ==="
        kubectl cluster-info || {
          echo "Cannot get cluster info"
          echo ""
          echo "=== Config view ==="
          kubectl config view
          echo ""
          echo "=== Check API server ==="
          curl -k https://127.0.0.1:6443/healthz || echo "API not responding"
          exit 1
        }

    - name: Verify cluster
      run: |
        export PATH=$PATH:./kubebuilder/bin
        export KUBECONFIG=$HOME/.kube/config
        
        echo "=== Nodes ==="
        kubectl get nodes -o wide || echo "Nodes check failed"
        
        echo ""
        echo "=== System pods ==="
        kubectl get pods -A || echo "Pods check failed"
        
        echo ""
        echo "=== Component status ==="
        kubectl get componentstatuses || echo "Status check failed"
        
        echo ""
        echo "=== API health ==="
        kubectl get --raw=/healthz || echo "Health check failed"
        
        echo ""
        echo "=== Server version ==="
        kubectl version || echo "Version check failed"

    - name: Create test deployment
      run: |
        export PATH=$PATH:./kubebuilder/bin
        export KUBECONFIG=$HOME/.kube/config
        
        echo "=== Creating nginx deployment ==="
        kubectl create deployment nginx --image=nginx:latest || {
          echo "Deployment failed"
          kubectl get events --sort-by='.lastTimestamp'
          exit 1
        }
        
        echo ""
        echo "=== Waiting for ready ==="
        kubectl wait --for=condition=available --timeout=60s deployment/nginx || {
          echo "Deployment not ready"
          kubectl get deployment nginx -o wide
          kubectl get pods -l app=nginx -o wide
          kubectl describe pods -l app=nginx
          exit 1
        }
        
        echo ""
        echo "=== Final status ==="
        kubectl get deployments
        kubectl get pods -l app=nginx -o wide

    - name: Test service
      run: |
        export PATH=$PATH:./kubebuilder/bin
        export KUBECONFIG=$HOME/.kube/config
        
        echo "=== Creating service ==="
        kubectl expose deployment nginx --port=80 --type=NodePort
        
        echo ""
        echo "=== Service details ==="
        kubectl get svc nginx -o wide
        kubectl describe svc nginx

    - name: Diagnostics
      if: always()
      run: |
        echo "=== System info ==="
        uname -a
        
        echo ""
        echo "=== Processes ==="
        ps aux | grep -E 'kube|etcd|containerd' | grep -v grep || true
        
        echo ""
        echo "=== Network ==="
        sudo netstat -tlnp | grep -E ':(6443|2379|10250)' || true
        
        echo ""
        echo "=== Directory structure ==="
        sudo ls -lah /var/lib/kubernetes/ || true
        sudo ls -lah /var/lib/kubernetes/pki/ || true

    - name: Collect logs
      if: always()
      run: |
        mkdir -p k8s-logs
        
        sudo journalctl -u kube-apiserver --no-pager > k8s-logs/apiserver.log 2>&1 || echo "No logs" > k8s-logs/apiserver.log
        sudo journalctl -u kube-controller-manager --no-pager > k8s-logs/controller.log 2>&1 || echo "No logs" > k8s-logs/controller.log
        sudo journalctl -u kube-scheduler --no-pager > k8s-logs/scheduler.log 2>&1 || echo "No logs" > k8s-logs/scheduler.log
        sudo journalctl -u kubelet --no-pager > k8s-logs/kubelet.log 2>&1 || echo "No logs" > k8s-logs/kubelet.log
        sudo journalctl -u etcd --no-pager > k8s-logs/etcd.log 2>&1 || echo "No logs" > k8s-logs/etcd.log
        sudo journalctl -u containerd --no-pager > k8s-logs/containerd.log 2>&1 || echo "No logs" > k8s-logs/containerd.log
        
        if [ -d "/var/log/kubernetes" ]; then
          sudo cp -r /var/log/kubernetes/* k8s-logs/ 2>&1 || true
        fi
        
        cp "$HOME/.kube/config" k8s-logs/kubeconfig.yaml 2>&1 || true
        
        export PATH=$PATH:./kubebuilder/bin
        export KUBECONFIG=$HOME/.kube/config
        kubectl get all -A -o wide > k8s-logs/resources.txt 2>&1 || true
        kubectl get events -A --sort-by='.lastTimestamp' > k8s-logs/events.txt 2>&1 || true
        kubectl describe nodes > k8s-logs/nodes.txt 2>&1 || true

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: k8s-logs
        path: k8s-logs/
        retention-days: 7

    - name: Upload binary
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: k8s-installer
        path: k8s-installer
        retention-days: 30